train_data: /data/jikaiyu/dataset/360-SOD/360-SOD-tr/imgs/
train_gt : /data/jikaiyu/dataset/360-SOD/360-SOD-tr/gts/
test_data: /data/jikaiyu/dataset/360-SOD/360-SOD-te/imgs/
val_list : ./data/vallist.txt
test_list: /data/jikaiyu/dataset/360-SOD/360-SOD-te/gts/
checkpoints : ./checkpoints
logs : ./Logs
result : ./Results
model_name : SCFANet
testset_name: 360-SOD-te
equi_input_width : 1024
equi_input_height : 512
cubemap_width : 256
num_classes : 1
batch_size : 2  
lr : 2.0e-3 
momentum : 0.9
power : 0.9
step_ratio : 0.8
weight_decay : 0.0005
epochs : 50
summary_freq : 1
test_mode: True
train_mode: False
use_gpu: True
device_id : 0
processes : 8
model_id: 40
